esphome:
  name: esphome-web-69d058
  friendly_name: pohybove_cidlo_esp32_c3
  min_version: 2025.9.0
  name_add_mac_suffix: false

  on_boot:
    priority: 800
    then:
      # --- 1. PRIPOJENIE ---
      - wait_until:
          condition:
            api.connected:
          timeout: 30s

      # --- 2. MERANIE A ODOSLANIE ---
      - delay: 500ms
      
      - component.update: battery_voltage
      - delay: 100ms 
      
      - component.update: battery_level
      
      - delay: 2s 

      # --- 3. LOGIKA ---
      - if:
          condition:
            not:
              api.connected:
          then:
            - deep_sleep.enter: deep_sleep_component

      - if:
          condition:
            binary_sensor.is_on: servisny_mod
          then:
            - deep_sleep.prevent: deep_sleep_component
          else:
            - wait_until:
                condition:
                  binary_sensor.is_off: pir_sensor
                timeout: 15s 

            - deep_sleep.enter: deep_sleep_component

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  baud_rate: 0

api:

ota:
  password: zadajte svoje heslo do ""
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: XXX.XXX.XXX.XXX 
    gateway: XXX.XXX.XXX.XXX   
    subnet: XXX.XXX.XXX.XXX

  fast_connect: true
  power_save_mode: NONE

deep_sleep:
  id: deep_sleep_component
  run_duration: 60s
  sleep_duration: 60min
  
  wakeup_pin:
    number: GPIO4
    mode: INPUT_PULLDOWN
    inverted: false
    allow_other_uses: true 

# --- HARDVÉR ---

sensor:
  # Batéria - Napätie
  - platform: adc
    pin: GPIO0
    id: battery_voltage
    name: "Battery Voltage"
    update_interval: never
    attenuation: 12db
    filters:
      - multiply: 2.0 

  # Batéria - Percentá
  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    device_class: battery
    update_interval: never
    force_update: true 
    lambda: |-
      if (std::isnan(id(battery_voltage).state)) { return {}; }
      if (id(battery_voltage).state < 3.2) { return 0; }
      else if (id(battery_voltage).state > 4.2) { return 100; }
      else { return (id(battery_voltage).state - 3.2) * 100.0 / 1.0; }
    accuracy_decimals: 0

binary_sensor:
  # Pohybový senzor (PIR)
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLDOWN
      allow_other_uses: true
    name: "Pohyb"
    id: pir_sensor
    device_class: motion
    filters:
      # Skrátené časy pre rýchlejšiu odozvu a rýchlejšie uspanie
      - delayed_on: 50ms 
      - delayed_off: 500ms

  # Servisný prepínač
  - platform: homeassistant
    id: servisny_mod
    entity_id: input_boolean.senzor_servis
    internal: true
